server {
    # Puerto CWMP/TR-069 estándar (co-ubicado en IP única del lab).
    listen 7547;
    server_name _;
    server_tokens off;

    # Banner falso de RomPager (CVE-2014-9222 Misfortune Cookie sim)
    add_header Server "RomPager/4.07 UPnP/1.0" always;

    location / {
        return 401 "Unauthorized";
    }

    location /web/ {
        return 200 "TR-069 CWMP endpoint";
    }
}
